# Generated by Django 2.2 on 2019-04-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160406_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='season',
            field=models.CharField(max_length=200),
        ),
    ]
